variable "vpcid" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "highcpu" {}
variable "lowcpu" {}
variable "ami" {}
variable "instance_type" {}
variable "public_key_path" {}
variable "userdata" {}
variable "db_storage" {}
variable "dbinstance_class" {}
variable "dbpassword" {}
variable "dbsubnet" {}
variable "rds_name" {}
variable "dbuser" {}
variable "env_name" {}
variable "vpc_id" {}
