apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.environment }}-frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: NodePort 
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
